// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDMseYwBozNNFrKBRlRa8p8_FazDk3RU',
    appId: '1:693529173976:web:121cfe684c63c78b685cad',
    messagingSenderId: '693529173976',
    projectId: 'teamwork-aeab1',
    authDomain: 'teamwork-aeab1.firebaseapp.com',
    storageBucket: 'teamwork-aeab1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7E36MOStOBeVmFer7iKKgW3FX2x2cVDo',
    appId: '1:693529173976:android:6acc524f4c566d52685cad',
    messagingSenderId: '693529173976',
    projectId: 'teamwork-aeab1',
    storageBucket: 'teamwork-aeab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkAp2WS001LdqYVHhHu8u4fkWbU0qKoU',
    appId: '1:693529173976:ios:9fe1dda93695a988685cad',
    messagingSenderId: '693529173976',
    projectId: 'teamwork-aeab1',
    storageBucket: 'teamwork-aeab1.appspot.com',
    iosBundleId: 'com.example.teamSyncPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkAp2WS001LdqYVHhHu8u4fkWbU0qKoU',
    appId: '1:693529173976:ios:2c9aa41b45e0b1c0685cad',
    messagingSenderId: '693529173976',
    projectId: 'teamwork-aeab1',
    storageBucket: 'teamwork-aeab1.appspot.com',
    iosBundleId: 'com.example.teamSyncPro.RunnerTests',
  );
}
